controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

admin_type_list:
    path: /admin/types
    controller: App\Controller\admin\AdminTypeController::listType

admin_type_show:
    path: /admin/type/{id}
    controller: App\Controller\admin\AdminTypeController::showType